### ISSUE TITLE
Pressing up arrow key shows the second last option

### ISSUE THREAD

**Issue by sant123** [sullof/inquirer-command-prompt#6]
Hi, I have these options that have been typed:

+ clear
+ help
+ P
+ ~Q

If I press the `up` arrow key I get `P` and not the last one that is `~Q`.

Thank you!

**Comment by sullof** [comment]
I am using the prompt in secrez (which is a command line secrets manager I am working on for a while). Using it I tried to replicate the problem you have. As you can see in the following screenshot, it is working as expected. Can you provide some code that I can replicate, please?

<img width="351" alt="screen shot 2018-03-05 at 11 12 41 am" src="https://user-images.githubusercontent.com/108464/36994541-4817092c-2066-11e8-9a91-491aef07fa5d.png">

**Comment by sant123** [comment]
Please take a look:

![test](https://user-images.githubusercontent.com/7959437/36995456-1c9cea48-2082-11e8-8adc-6ce31d7bb03f.gif)

The first time works, it's okay. But note the last thing I type `P->Q`. When I press arrow key up, should the last one be shown?

**Comment by sullof** [comment]
Ok, I see the problem.

Suppose that you type (the number indicates the index in the history array):
```
a      0   
b      1
c      2
b      3
d      4
```
Suppose that now you press up 4 times and press [enter], you will recover the b at index 1.
You would see something like:
```
a      0   
b      1
c      2
b      3
d      4
b      5
```
If after you press up 2 times, instead of seeing the `d` at position 4, since it was positioned at 1 before, it will show you the `a`.

This explain that weird behavior.
I guess it is necessary to reset the position in the index.
I will try to fix it asap.
Thanks.

**Comment by sant123** [comment]
To you @sullof 😄

**Comment by sullof** [comment]
This has been fixed in a recent version. Try the 0.0.13.

**Comment by sullof** [comment]
@sant123 
BTW, I apologize for not working on this for so long.
